In [7]:
import numpy as np

# Create a random vector of size 15 having integers in the range 1-20
rand_vec = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
rand_mat = rand_vec.reshape((3, 5))

# Print the array shape
print("Shape of the array:", rand_mat.shape)

# Replace the max in each row by 0
rand_mat[np.arange(3), rand_mat.argmax(axis=1)] = 0

# Create a 2-dimensional array of size 4 x 3
arr = np.zeros((4, 3), dtype=np.int32)

# Print the shape, type and data type of the array
print("Shape of the array:", arr.shape)
print("Type of the array:", type(arr))
print("Data type of the array:", arr.dtype)


Shape of the array: (3, 5)
Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [2]:
import numpy as np

# Define the square array
A = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:")
for i in range(len(eigenvectors)):
    print(eigenvectors[:, i])


Eigenvalues: [2. 1.]
Right Eigenvectors:
[0.89442719 0.4472136 ]
[0.70710678 0.70710678]


In [3]:
import numpy as np

# Define the array
A = np.array([[0, 1, 2], [3, 4, 5]])

# Compute the sum of diagonal elements of A
diag_sum = np.trace(A)

# Print the sum of diagonal elements
print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [4]:
import numpy as np

# Define the array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to 2x3
arr_2x3 = np.reshape(arr, (2, 3))

# Reshape the array back to 3x2
arr_3x2 = np.reshape(arr_2x3, (3, 2))

# Print the original array and the reshaped arrays
print("Original Array:\n", arr)
print("Reshaped Array (2x3):\n", arr_2x3)
print("Reshaped Array (3x2):\n", arr_3x2)


Original Array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped Array (3x2):
 [[1 2]
 [3 4]
 [5 6]]
